### ISSUE TITLE
Optimize loading time when inline-edit is active.

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#68] opened 2015-01-07 09:58 UTC
For testing only:
```
var checkExist = setInterval(function() {
if (document.getElementById("cacie-toggle-edit")) {
document.getElementById("cacie-toggle-edit").click();
clearInterval(checkExist);
}
}, 200); // check every 200ms
```

Which allows the products to load in the same amount of time as they usually do (not adding the three seconds), and then clicks your inline-edit button which only takes 1 / 4th of a second to initiate. I don't know why the other method takes so long because, technically, my method is less efficient. Do you have any idea? Maybe it tries to load too soon and gets stuck for a bit?

by Joel

**Comment by engelen** [comment] 2015-02-19 09:14
We're unable to reproduce this issue; closing as wontfix.

**Closed by engelen** 2015-02-19 09:14 UTC
Labels: enhancement, wontfix
