### ISSUE TITLE
Inline edit error on enter

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-pro-issues#65] opened 2015-01-07 09:51 UTC
I seem to get this 5% of the time after I press "Enter" when editing a value. If I get the error and then press "Enter" again, it goes through just fine, have you seen this in any of your testing? Maybe I'm entering in values too fast one after another?

![screen shot 2014-12-17 at 12 50 43 pm](https://cloud.githubusercontent.com/assets/2736280/5643635/21259c4a-965b-11e4-9c80-c0adf3c07c47.png)

by Joel

**Comment by engelen** [comment] 2015-01-21 08:53
I am unable to reproduce this issue. Where does this question originate? A few questions arise. For example, does he get this error at every field type, or just at a specific one? Is he editing posts, users, or something else?

**Comment by engelen** [comment] 2015-02-15 21:17
I still can't reproduce this issue, just as I couldn't reproduce it from the original ticket. Marking and closing as wontfix, unless there are steps to reproduce this.

**Closed by engelen** 2015-02-15 21:17 UTC
Labels: bug
